@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class "{abstract}\nPerson" as Person

Class "<<enumeration>>\nContactType" as ContactType

AddressBook *-down-> "1" UniquePersonList

UniquePersonList -down-> "*" Person

Person -down-> "*" Tag
Person .right.> ContactType

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
Person *--> Note

Customer -down-|> Person
Staff -right-|> Person
Supplier --|> Person

Customer *-up-> Points

Supplier *-up-> "1..*" Items
Supplier *-right-> "1..*" Days

Staff *-left-> "1..*" Shift

@enduml
